FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    mininet \
    openvswitch-switch \
    iputils-ping \
    iperf \
    iperf3 \
    python3 \
    python3-pip \
    net-tools \
    iproute2 \
    curl \
    nano \
    && rm -rf /var/lib/apt/lists/*

# Install ryu and requests. We also install eventlet < 0.30 because ryu has a bug with newer eventlet on py3.8
RUN pip3 install "eventlet<0.30.0" ryu requests

WORKDIR /app

# Ensure Open vSwitch starts before executing any command
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["/bin/bash"]
